export const site = {
	name: 'Knitting Tools',
	tagline: 'Free tools for knitting — pick what you need.',
	catalogHeading: 'Tools',
	backToCatalog: 'All tools'
} as const;

export const jacquard = {
	sectionImage: 'Image',
	sectionCrop: 'Crop',
	sectionDimensions: 'Dimensions',
	sectionGauge: 'Needle/row ratio',
	sectionConvert: 'Conversion',
	sectionExport: 'Export',
	upload: 'Drop an image here or click to browse',
	fitProportions: 'Fit proportions',
	stitches: 'Width (stitches)',
	stitchesPerCm: 'Stitches per cm',
	rowsPerCm: 'Rows per cm',
	rowsComputed: 'Rows (computed)',
	dimensionsSummary: (p: { stitches: string; rows: string; widthCm: string; heightCm: string }) =>
		`${p.stitches} stitches × ${p.rows} rows — about ${p.widthCm} × ${p.heightCm} cm on fabric`,
	threshold: 'Black / white balance',
	invert: 'Invert colors',
	fabricView: 'As on fabric',
	exportAyab: 'Export for AYAB',
	exportDocs: 'Export documentation',
	legendBackground: 'Background',
	legendForeground: 'Foreground',
	warnOverNeedles: 'This exceeds the 200-needle machine limit.',
	warnLongPattern: 'Very long pattern — check row count before knitting.',
	confirmOverNeedles: 'Width is over 200 stitches. Export anyway?',
	errorUnsupportedType: 'Unsupported format. Use JPG, PNG, or WebP.',
	errorFileTooLarge: 'Image is too large. Try a smaller file.',
	hintUpload: 'Upload an image to get started.',
	stepBack: 'Back',
	stepNext: 'Next',
	preview: 'Preview',
	fabricViewHint: 'Shows how the pattern will look on fabric, using your needle/row ratio.'
} as const;

export const intarsia = {
	projectName: 'Project name',
	newProject: 'New project',
	exportProject: 'Export project',
	importProject: 'Import project',
	uploadImage: 'Upload image',
	createGrid: 'Create grid',
	widthStitches: 'Width (stitches)',
	heightRows: 'Height (rows)',
	colourCount: 'Number of colours',
	confirmColours: 'Confirm colours',
	mergeColours: 'Merge colours',
	addColour: 'Add colour',
	removeColour: 'Remove colour',
	confirmRemoveColourInUse: (name: string) =>
		`"${name}" is used on the grid. Remove it anyway? Stitches in this colour will become white.`,
	errorCannotRemoveColour: 'Cannot remove this colour.',
	rowLabel: (n: number) => `Row ${n}`,
	nextRow: 'Next row',
	prevRow: 'Prev row',
	prevStitch: 'Previous stitch',
	nextStitch: 'Next stitch',
	readingAuto: 'Auto (zigzag)',
	readingManual: 'Manual',
	directionLtr: 'Left to right',
	directionRtl: 'Right to left',
	showRsWs: 'Show RS/WS',
	fabricView: 'As on fabric',
	stitchesPerCm: 'Stitches per cm',
	rowsPerCm: 'Rows per cm',
	zoom: 'Zoom',
	totalStitches: (n: number) => `${n} stitches`,
	editPatternWarning: 'Editing the pattern may change instructions for the current row. Continue?',
	errorUnsupportedType: 'Unsupported format. Use JPG or PNG.',
	errorFileTooLarge: 'Image too large. Try a smaller file.',
	errorPatternExceedsLimits: 'Pattern exceeds 200 stitches or 300 rows.',
	errorTooManyColours: 'Maximum 20 colours. Merge colours in the review step.',
	errorNoPattern: 'Load or create a pattern to start.',
	errorInvalidProject: 'Could not read project file.',
	confirmNewProject: 'Start a new project? This replaces your current project.',
	hintStart: 'Load or create a pattern to get started.'
} as const;

export const dataPattern = {
	stepSource: 'Source',
	stepConfigure: 'Configure',
	stepGenerate: 'Generate',
	sourceVoice: 'Record from microphone',
	sourceAudio: 'Upload MP3, WAV, or OGG',
	sourceTerrain: 'Pick a place on the map',
	runsLocally: 'Runs locally',
	usesExternalMap: 'Uses external map data',
	whatIsSent: 'What is sent?',
	continue: 'Continue',
	back: 'Back',
	generatePattern: 'Generate pattern',
	sensitivity: 'Sensitivity',
	smoothing: 'Smoothing',
	analysisMode: 'Analysis mode',
	modeWaveform: 'Waveform',
	modeSpectrogram: 'Spectrogram',
	terrainContinuous: 'Continuous elevation',
	terrainPosterized: 'Posterized relief',
	posterizeLevels: 'Posterize levels',
	stitches: 'Width (stitches)',
	stitchesPerCm: 'Stitches per cm',
	rowsPerCm: 'Rows per cm',
	dimensionsSummary: (p: { stitches: string; rows: string; widthCm: string; heightCm: string }) =>
		`${p.stitches} sts × ${p.rows} rows — approx. ${p.widthCm} × ${p.heightCm} cm on fabric`,
	changeSource: 'Change source',
	resetToGenerated: 'Reset to generated',
	viewSymbols: 'Symbols',
	viewJacquard: 'Jacquard colours',
	exportKnitPurl: 'Knit/purl chart',
	exportJacquard: 'Jacquard (2 colours)',
	downloadPdfChart: 'Download PDF chart',
	downloadSymbolicPng: 'Download symbolic PNG',
	downloadAyabPng: 'Download AYAB PNG',
	downloadAnnotatedPdf: 'Download annotated PDF',
	fabricView: 'As on fabric',
	threshold: 'Black / white balance',
	contrast: 'Contrast',
	invert: 'Invert',
	warnOverStitches: 'This exceeds the 200-stitch machine limit.',
	confirmOverStitches: 'Width is over 200 stitches. Export anyway?',
	warnRowsCapped: 'Pattern capped at 300 rows. Use a shorter clip or smaller area.',
	warnShortPattern: 'Pattern is very short — try a longer recording or wider area.',
	warnFlatInput: 'Input looks uniform — try increasing contrast or sensitivity.',
	confirmChangeSource: 'Your pattern edits will be lost. Continue?',
	confirmRefineDiscard: 'Changing refine settings will discard manual edits. Continue?',
	confirmReset: 'Discard manual edits and restore from source data?',
	errorMicDenied: 'Microphone access denied. Allow access in browser settings to use Voice mode.',
	errorNoWebAudio: "This browser doesn't support audio analysis. Try Chrome or Firefox.",
	errorUnsupportedAudio: 'Unsupported format. Use MP3, WAV, or OGG.',
	errorAudioTooLarge: 'File too large. Try a shorter clip or lower bitrate.',
	errorAudioDecode: 'Could not read this audio file. Try converting to WAV.',
	errorSegmentTooShort: 'Select a segment with at least 1 second of audio.',
	errorPlaceNotFound: 'No location found. Try a different spelling.',
	errorGeocoding: 'Place search is unavailable. Pan the map to your area.',
	errorElevation: 'Could not fetch elevation data. Check your connection and try again.',
	errorBboxTooLarge: 'Selected area is too large. Zoom in or shrink the selection box.',
	retry: 'Retry',
	legendKnit: 'Knit',
	legendPurl: 'Purl',
	record: 'Record',
	stop: 'Stop',
	searchPlace: 'Search place',
	generating: 'Generating pattern…',
	generationFailed: 'Could not generate pattern.',
	backToConfigure: 'Back to configure'
} as const;
